version: '3.1'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django